
import os
import json
from django.shortcuts import render
from django.http import JsonResponse
from django.conf import settings

def index(request):
    # Static Data Loading (Low Memory)
    # We load the pre-calculated stats from the JSON file generated by the script
    json_path = os.path.join(settings.BASE_DIR, 'api/static/api/assets/clusters_data.json')
    
    context = {}
    if os.path.exists(json_path):
        with open(json_path, 'r') as f:
            data = json.load(f)
            # data structure: {'n_clusters': 6, 'cluster_centers': [...], 'counts': {'0': 123...}}
            context['n_clusters'] = data.get('n_clusters', 6)
            context['counts'] = data.get('counts', {})
            
    return render(request, 'api/index.html', context)

def clusters_data(request):
    json_path = os.path.join(settings.BASE_DIR, 'api/static/api/assets/clusters_data.json')
    if os.path.exists(json_path):
        with open(json_path, 'r') as f:
            data = json.load(f)
        return JsonResponse(data)
    return JsonResponse({'error': 'Data not found'}, status=404)
