
import os
import json
from django.shortcuts import render
from django.http import JsonResponse
from django.conf import settings

def index(request):
    # Static Data Loading (Low Memory)
    # We load the pre-calculated stats from the JSON file generated by the script
    json_path = os.path.join(settings.BASE_DIR, 'api/static/api/assets/clusters_data.json')
    
    # Get user input for simulation (default to 6)
    user_n_clusters = request.GET.get('n_clusters', 6)
    
    context = {}
    if os.path.exists(json_path):
        with open(json_path, 'r') as f:
            data = json.load(f)
            # Use user input for the UI label to simulate "dynamic" behavior
            context['n_clusters'] = user_n_clusters
            
            # Calculate percentages
            counts_dict = data.get('counts', {})
            total = sum(counts_dict.values())
            cluster_stats = []
            for cid, count in counts_dict.items():
                pct = (count / total * 100) if total > 0 else 0
                cluster_stats.append({
                    'id': cid,
                    'count': count,
                    'pct': round(pct, 2)
                })
            # Sort numerically if possible
            cluster_stats.sort(key=lambda x: int(x['id']) if x['id'].isdigit() else x['id'])
            
            context['cluster_stats'] = cluster_stats
            
    return render(request, 'api/index.html', context)

def clusters_data(request):
    json_path = os.path.join(settings.BASE_DIR, 'api/static/api/assets/clusters_data.json')
    if os.path.exists(json_path):
        with open(json_path, 'r') as f:
            data = json.load(f)
        return JsonResponse(data)
    return JsonResponse({'error': 'Data not found'}, status=404)
